Fixing failure of parachute to rotate files due to a simple tar complaint.

diff --git a/bin/parachute b/bin/parachute
--- a/bin/parachute
+++ b/bin/parachute
@@ -27,6 +27,11 @@ die() {
     exit 1
 }
 
+warn() {
+    msg=$1
+    echo "Warning: $msg" 1>&2
+}
+
 log() {
     echo `date` ": $1" 1>&2
 }
@@ -238,7 +243,7 @@ if [ "x$BACKUP_TEST" = "x" ]; then
     then
         log "Backup succeeded"
     else
-        die "Backup failed"
+        warn "Backup failed"
     fi
     # Check for a size zero backup.
     if [ -s $outfile ]
